### ISSUE TITLE
Return False always

### ISSUE THREAD

**Issue by Joozty** [prodicus/vocabulary#23]
Hi. I installed successfully this package. (no errors). I try your examples 
```
from vocabulary import Vocabulary as vb
print(vb.meaning('car'))
print(vb.synonym('car'))
```

Python version 3.5.2 (2.7.12) - I tried it on windows and linux and same result. 
It returns me always **false** no matter what word I use. 

only this works:
`print(vb.hyphenation('car'))
`

[{"text": "car", "seq": 0}]

Thanks for help

**Comment by FreddieSun** [comment]
Same problem, any idea?
