### ISSUE TITLE
[Problems] Inconsistent data

### ISSUE THREAD

**Issue by tenorz007** [prodicus/vocabulary#27]
- [x] Pronunciation 'seq' key is always set to 0
- [x] PartOfSpeech doesn't return all data gotten from API, only returns the first
- [x] Antonym value is always a list (Known Issue) and doesn't return all data gotten from the API; this is because the API returns a list and the package handles it as if its a text and just sets it without parsing it first

**Comment by prodicus** [comment]
@tenorz007 Looks like these bugs have been around for quite some time now. If you are willing to take it, should I assign this issue to you?

**Comment by tenorz007** [comment]
Yeah, I can take it up.

**Comment by tenorz007** [comment]
The fixes would interfere with some of the tests, so I'd wait till that's been merged before I work on it.

**Comment by prodicus** [comment]
@tenorz007 Sure thing. Will review your PR #26 at my earliest. 👍

**Comment by tenorz007** [comment]
@prodicus So I have pulled up fixes for these but the test will fail so I need the other PR's first.

**Comment by prodicus** [comment]
@tenorz007 Closed #26 . You can work on this issue now. Also, please check the last thread on that PR.

**Comment by tenorz007** [comment]
@prodicus In a way yes, but ideally it should be of the format major:minor:patch {*}
From what I understand:
* major is updated when it could break existing functionality no backward compatibility possibly
* minor is updated for new features basically
* patch is updated for things like bug fixes
