### ISSUE TITLE
Returning False in odd places

### ISSUE THREAD

**Issue by gdude2002** [prodicus/vocabulary#5]
Here's some examples.
- https://github.com/prodicus/vocabulary/blob/master/vocabulary/vocabulary.py#L66
- https://github.com/prodicus/vocabulary/blob/master/vocabulary/vocabulary.py#L174
- https://github.com/prodicus/vocabulary/blob/master/vocabulary/vocabulary.py#L214

There's a lot of this. Why `False`? Shouldn't you be returning `None` instead? `None` is still "falsey", so you can still say `if not result:`, but more correctly denotes the lack of any data to return.

**Comment by prodicus** [comment]
I appreciate your concern, but don't both kind of give the same meaning in this context? Although I would like to hear any disadvantages for returning `False`

**Comment by gdude2002** [comment]
It's mostly a convention, think of it like if you were asking a question.

"What synonyms are there for this word?" "False."

That doesn't make sense, right?

"Are there any synonyms for this word?" I'd expect True or False here.
" What synonyms are there for this word?" I'd expect a list of synonyms here - or an empty list, `[]`, or `None` to mean "No synonyms".

**Comment by prodicus** [comment]
Sounds legit. Will work on it.

**Comment by siddhanjay** [comment]
Can I take up this issue ?

**Comment by prodicus** [comment]
@siddhanjay :+1:

**Comment by Matthewrbowker** [comment]
#23 is possibly related to this issue.

**Comment by prodicus** [comment]
Closed by 7573f21. 

feel free to reopen it again if not the case @Matthewrbowker @gdude2002
