### ISSUE TITLE
Odd requirements.txt

### ISSUE THREAD

**Issue by gdude2002** [prodicus/vocabulary#7]
The `requirements.txt` file should be a list of packages required by your package, for parsing by `pip`.

In your `requirements.txt`, we have the following:

```
requests==2.8.1
Vocabulary==0.0.3
wheel==0.26.0
```

* `requests==2.8.1` - Why this version? Is there some quirk you require? If you're just using the normal API, you can leave out the explicit version and just use `requests` here.
* `Vocabulary==0.0.3` - This is your package, right? This could cause some nasty dependency loops in `pip`, it shouldn't be here.
* `wheel==0.26.0` - Why? Where are you using `wheel`?

**Comment by prodicus** [comment]
Jeez. :smile:  I accidentally did a `$ pip freeze > requirements.txt` when I was testing the package inside a `virtualenv`.

Forgot to remove it. Doing it now. :+1:

**Comment by gdude2002** [comment]
Heh, yeah, it's a good idea to check over the files you're committing before you actually commit them. :wink:

**Comment by prodicus** [comment]
Will keep it in mind :smile:

**Comment by prodicus** [comment]
Fixed it in  295ee0b.

Closing issue
