### ISSUE TITLE
Contribute more backends, extend API

### ISSUE THREAD

**Issue by balta2ar** [prodicus/vocabulary#9]
I've looked over your project and it seems to be very interesting. In fact I've done something similar for my own purposes. My goal, however, was to build a small set of tools to 1) extract words from my dictionary 2) obtain translation/usage/examples/synonyms etc 3) show that in conky 4) convert that to Anki format for future learning. Take a look if you're interested: https://github.com/balta2ar/yandex-slovari-tetradki/

I've implemented a small set of backends for slightly different sites, the implementation might be not very robust and production ready (it rather scrapes the HTML code, not API), but I still think we have common ideas in our implementations. In this issue I wanted to inquire whether you think that support for additional sites (something along the sites that my script supports) would be appropriate in your project?

**Comment by prodicus** [comment]
Hey @balta2ar . Your module looks good and I think it is doing something very similar to what Vocabulary is trying to do.

I am all in support for adding new functions to this module and I will be adding the translate module to Vocabulary shortly. 

So what extra features or websites do you have in your mind?

**Comment by balta2ar** [comment]
The most interesting to me are priberam.pt, Yandex.Translate and Thesaurus.com (you already have synonyms so it is not that important), I think. I was also thinking about adding Google Dictionary, it looks nice as well.

Anyway, I've got your opinion on that and I like that you're open for suggestions. I'd love to see how your development goes and hopefully I will be able to contribute something valuable too.

**Comment by prodicus** [comment]
That's kind of you @balta2ar . And I would be more than happy for contributions on Vocabulary :smile:
